### ISSUE TITLE
No puedo subir cambios

### ISSUE THREAD

**Issue by amuela** [jjeg1979/LeapFrog#1]
¿quizás tienes que darme permisos como contributor?

**Comment by jjeg1979** [comment]
Pues puede...dejame que mire y te digo...

**Comment by amuela** [comment]
Correcto y funcionando

**Comment by jjeg1979** [comment]
De PM!!!

Me alegro!

JJ

2015-03-30 9:26 GMT+02:00 Alfredo Muela notifications@github.com:
